name: Continuous Delivery

on:
  push:
    branches:
      - main

env:
  AWS_REGION_DEFAULT: us-east-1
  AWS_UPLOAD_API_ECR_REPOSITORY: video-processor-hackathon/upload-api
  AWS_LIST_PROCESSING_STATUS_API_ECR_REPOSITORY: video-processor-hackathon/list-processing-status
  AWS_LAMBDA_FUNCTION_NAME: GetPresignedUrl
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION_DEFAULT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform ECR
        working-directory: infrastructure/ecr
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image - GetPresignedURL
        run: |
          IMAGE_URI_GET_PRESIGNED_URL="${{ steps.login-ecr.outputs.registry }}/${{ env.AWS_UPLOAD_API_ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          docker build -t "$IMAGE_URI_GET_PRESIGNED_URL" -f Dockerfile.getPresignedUrl .
          echo "IMAGE_URI_GET_PRESIGNED_URL=$IMAGE_URI_GET_PRESIGNED_URL" >> $GITHUB_ENV

      - name: Push image to ECR - GetPresignedURL
        run: |
          docker push "$IMAGE_URI_GET_PRESIGNED_URL"

      - name: Build Docker image - ListProcessingStatus
        run: |
          IMAGE_URI_LIST_PROCESSING_STATUS="${{ steps.login-ecr.outputs.registry }}/${{ env.AWS_LIST_PROCESSING_STATUS_API_ECR_REPOSITORY }}${{ env.IMAGE_TAG }}"
          docker build -t "$IMAGE_URI_LIST_PROCESSING_STATUS" -f Dockerfile.listProcessingStatus .
          echo "IMAGE_URI_LIST_PROCESSING_STATUS=$IMAGE_URI_LIST_PROCESSING_STATUS" >> $GITHUB_ENV

      - name: Push image to ECR - ListProcessingStatus
        run: |
          docker push "$IMAGE_URI_LIST_PROCESSING_STATUS"

      - name: Terraform Init and Apply for Lambda + API Gateway
        working-directory: infrastructure/lambda
        env:
          TF_VAR_image_tag: ${{ env.IMAGE_TAG }}
        run: |
          terraform init
          terraform apply -auto-approve
